function SC=vec2screw(v,r)

%VEC2SCREW transforms line direction v and a point r on the line to screw vector 
%	-v is the screw axis direction vector 
%	-r is a point on the axis
%	SC is the screws generated by v and r

% wrong format
sv=size(v);
sr=size(r);
if sv==[1 3]v=v';sv=size(v);end
if sr==[1 3],r=r';sr=size(r);end

% wrong format
if sv(1) ~= 3 || sr(1) ~= 3
    error('vec2screw:wrongsize.');
end

SC=sym(zeros(6,1));
SC(1:3,1)=v;
SC(4:6,1)=cross(r,v);